#!/usr/bin/env bash
# Transfers a file to the given server's ip via scp.
case "$#" in
    4)
        scp -i "$4" "$1" "$3@$2":~/
        ;;
    *)
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        ;;
esac
