#!/usr/bin/env bash
# Installs nginx and sets up the page to return "Holberton School".
apt-get update && apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
service nginx start
