#!/usr/bin/env bash
# Installs nginx and sets up the page to return "Holberton School".
apt-get update && apt-get install nginx -y

# Sets the content of the root nginx page.
echo "Holberton School" > /var/www/html/index.html

# Checks if there is a line having redirect_me.
# Declare input string.
IN_STRING="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
# Add line into the file.
sed -i "48i $IN_STRING" /etc/nginx/sites-available/default

service nginx stop
service nginx start
