#!/usr/bin/env bash
# Installs HAproxy and configures it to serve as a load balancer between 
apt-get update && apt-get install haproxy=1.6.\* -y

# Sets the content of the haproxy.cfg
echo '
frontend diego-lopez.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server server-01 34.75.21.202:80
        server server-02 35.185.122.161:80
' >> /etc/haproxy/haproxy.cfg

/etc/init.d/haproxy restart
