#!/usr/bin/env bash
# Prints the username userid and home directory path from the passwd file.
filename="/etc/passwd"

while _= read line
do
    username=$(echo "$line" | cut -d':' -f1)
    group_id=$(echo "$line" | cut -d':' -f2)
    home_dir=$(echo "$line" | cut -d':' -f3)
    cmdshell=$(echo "$line" | cut -d':' -f4)
    user__id=$(echo "$line" | cut -d':' -f5)
    password=$(echo "$line" | cut -d':' -f6)
    uid_info=$(echo "$line" | cut -d':' -f7)

    echo -n "The user $username is part of the $group_id gang, lives in "
    echo -n "$home_dir and rides $cmdshell. $user__id's place is protected by "
    echo "the passcode $password, more info about the user here: $uid_info"
done < $filename
